---
title: "R-Ladies YouTube Video Feed"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    navbar:
      - { icon: "fa-github", href: "https://github.com/ivelasq/rladies-video-feed", align: right }
    theme:
      version: 4
      bg: "#FDF7F7"
      fg: "#88398A" # purple
      primary: "#88398A" # purple
      base_font:
        google: "Lato"
---

```{r setup, include=FALSE}
library(flexdashboard)
library(bslib)
library(here)
source(
  here("R scripts", "r-ladies-data-processing.R"),
  local = knitr::knit_global()
  )
```

Channels {.sidebar}
-----------------------------------------------------------------------

The purpose of this dashboard is to provide a running feed of R-Ladies videos posted to YouTube. It is refreshed every 24 hours.

Currently, the feed includes these channels:

```{r}
dat_join %>% 
  dplyr::arrange(chapter) %>% 
  dplyr::distinct(channel_image_url) %>% 
  dplyr::pull() %>% 
  htmltools::HTML(.noWS = "outside")
```

Column {data-width=900}
-----------------------------------------------------------------------

### By default, the list is sorted by latest video.

<style>
.dataTables_scrollBody {
    max-height: 100% !important;
}
</style>

```{r}
library(googlesheets4)
gs4_auth(email = "danielamieva@dar4datascience.com")
# read in file
tbl_tidy_x_videos_processed <- read_sheet(ss = gs4_find("shiny-youtube-adhoc-search"),
              sheet = "TidyX Videos")

tbl_tidy_x_videos_processed |> 
DT::datatable(
  colnames = c('Date', 'Channel', 'Video', 'Episode Topics',
               'Description'),
  filter = 'top',
  escape = FALSE,
  height = '1000',
  #quitar search para episode topics
  elementId = 'dashboard',
  options = list(columnDefs = list(
    list(className = 'dt-middle', targets = "_all")
  ))
)

```
