name: rladies_videos_bot

on:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  render:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Github action for rmarkdown
        uses: lucharo/rmarkdown-action@v1
        with: index.Rmd
        output_format: html_document
