on: [push]

name: rladies-videos-bot

jobs:
  rladies-videos-bot:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2

      - name: Create and update dashboard
        run: |
          Rscript -e 'rmarkdown::render("index.Rmd", output_format = "html_document")'

        env:
          YOUTUBE_CLIENT: ${{ secrets.YOUTUBE_CLIENT }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}