name: rladies_videos_bot

on:
  schedule:
  - cron: '0 */12 * * *'

jobs:
  render:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install remotes package
        run: Rscript -e 'install.packages("remotes")'
      - name: Install tuber package
        run: Rscript -e 'install_github("soodoku/tuber")'
      - name: Install readr package
        run: Rscript -e 'install.packages("readr", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install stringr package
        run: Rscript -e 'install.packages("stringr", dependencies = TRUE)'
      - name: Install DT package
        run: Rscript -e 'install.packages("DT", dependencies = TRUE)'
      - name: Install rmarkdown package
        run: Rscript -e 'install.packages("rmarkdown", dependencies = TRUE)'  
      - name: Install shiny package
        run: Rscript -e 'install.packages("shiny", dependencies = TRUE)' 
      - name: Install flexdashboard package
        run: Rscript -e 'install.packages("flexdashboard", dependencies = TRUE)'  
      - name: Install bslib package
        run: Rscript -e 'install.packages("bslib", dependencies = TRUE)'  
      - name: Create and update dashboard
        run: Rscript -e 'rmarkdown::render("index.Rmd", output_format = "html_document")'
