on:
  schedule:
  - cron: '0 */1 * * *'
  
name: rladies_videos_bot

jobs:
  rladies_videos_bot-post:
  runs-on: macOS-latest
  steps:
      - uses: actions/checkout@main
      - uses: r-lib/actions/setup-r@v2
      - name: Install tidyRSS package
        run: Rscript -e 'install.packages("tidyRSS", dependencies = TRUE)'
      - name: Install readr package
        run: Rscript -e 'install.packages("readr", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install stringr package
        run: Rscript -e 'install.packages("stringr", dependencies = TRUE)'
      - name: Install DT package
        run: Rscript -e 'install.packages("DT", dependencies = TRUE)'
      - name: Install rmarkdown package
        run: Rscript -e 'install.packages("rmarkdown", dependencies = TRUE)'  
      - name: Install shiny package
        run: Rscript -e 'install.packages("shiny", dependencies = TRUE)' 
      - name: Install flexdashboard package
        run: Rscript -e 'install.packages("flexdashboard", dependencies = TRUE)'  
      - name: Install bslib package
        run: Rscript -e 'install.packages("bslib", dependencies = TRUE)'  
      - name: Create and update tweet
        run: Rscript -e 'rmarkdown::render("rladies-videos-doc.Rmd", output_format = "html_document")'
